### ISSUE TITLE
SRP acceptance/rejection DM from discord bot

### ISSUE THREAD

**Issue by DeathstrokeXCV** [ppfeufer/aa-srp#11]
When accepting/rejecting srp requests I am getting the messge from the discord bot for the requested ships and not the requester of the SRP. "Discord notification via PM to the user on SRP request approval or rejection, if AA-Discordbot is installed" am i reading this wrong?

**Comment by ppfeufer** [comment]
Yep, you are absolutely right, the requester should get the Discord PM. I'll have a look at it.

**Comment by ppfeufer** [comment]
This should fix it.

**Comment by ppfeufer** [comment]
New version - v1.0.1 released with a fix.

Thanks for reporting this!
