### ISSUE TITLE
[Feature Request] Configurable source for ship value

### ISSUE THREAD

**Issue by KaraHops** [ppfeufer/aa-srp#153]
### Context

The existing "isk lost" column seems to pull value from the "Total" loss value on zkillboard and does not take other data into account.

### Describe the feature you have in mind

It would be nice in the configuration for this add-on for it to be possible to configure the source of the value for the ship lost as the current default includes the value of loot that should not necessarily be covered by SRP. In particular, it would be nice to be able to pull this number from the "Ship+Fit" line on zkillboard instead.

Additionally, it would be nice to be able to configure the automatic subtraction of the value of insurance. A nice-to-have would be a dropdown to be able to select any level of insurance, but a simple checkbox to take platinum insurance into account would be most useful.

**Comment by ppfeufer** [comment]
If this is about the - more or less - automatic fill-in of the SRP payout value, you can manually change that for pending or rejected requests.

![image](https://github.com/ppfeufer/aa-srp/assets/2989985/b05c3870-7aea-4d4b-a9ee-9f573e8156ae)

The "ISK lost" column reflects the actual loss for the pilot (ship and all), which will only be used as payout value when simply accepting the request without setting a payout value before doing so.

**Comment by ppfeufer** [comment]
> Additionally, it would be nice to be able to configure the automatic subtraction of the value of insurance. A nice-to-have would be a dropdown to be able to select any level of insurance, but a simple checkbox to take platinum insurance into account would be most useful.

Please open a new feature request for this one :-)

**Comment by ppfeufer** [comment]
I've added a setting to select the loss value source. This will be in an upcoming release.

![image](https://github.com/ppfeufer/aa-srp/assets/2989985/e333711b-3d4c-4293-8ef0-c9fcb7942dba)

This setting will only affect new SRP requests.

**Comment by KaraHops** [comment]
Thanks Peter. Yes it's mostly a want about automating the calculation steps; in the current build the "isk lost" column is basically useless to us as we need to open the zkill link, copy the ship+fit value, subtract insurance, then paste that into the payout amount field before approving the request. Your addition to that upcoming release will at least let us do it all in one tab!
