### ISSUE TITLE
[Feature] Compare srp link and loss dates

### ISSUE THREAD

**Issue by paulipa** [ppfeufer/aa-srp#20]
As title says a boolen to indicate if the killmail link posted matches the srp link date to fast check if the loss has happened on the same day. Helps out a bit to filter out people who are trying to apply to SRP with losses that might have happened outside of the fleet date. To counter midnight fleets maybe add a check for +-12 hours from srp link date to return true.

**Comment by ppfeufer** [comment]
Not everyone has SRP links on a fleet by fleet basis. My old Alliance had them for example on a per week basis, my corp has them on a per year basis. This wouldn't work then.

This is what the "Additinal Informartion" field for the SRP request is for. To explain what happened, who was FC etc, etc, etc. If in doubt, ask the pilot.

**Comment by paulipa** [comment]
We do also have general srp links that are open for long period of times so not looking to add a timer check as a limitation to apply but something to speed up checking the links. A easy way to srp managers to know if the kill was within a day of the link created or not. Then they can decide whatever to do with it. Checking details and such is just too much work for me ^^

**Comment by ppfeufer** [comment]
You have to check the kill mail anyways, if the ship was fitted correctly and so on. At least that's how everyone I know does that. That's where you can have a look at the date as well.
