### ISSUE TITLE
No configuration option for discordproxy host and port

### ISSUE THREAD

**Issue by Exenifix** [ppfeufer/aa-srp#240]
https://github.com/ppfeufer/aa-srp/blob/55f3f0791c6022e8b4cbc1a795ebd33f745d9168/aasrp/discord/channel_message.py#L109

And all other occurrences where DiscordClient is used without passing host and port where discordproxy is running. Makes it basically impossible to use aa-srp in docker without publishing discordproxy's port

**Comment by ppfeufer** [comment]
`dicsordproxy` is not to be configured through `aasrp`.

`aasrp` merely imports the `DiscordClient`.

If you're using Docker, you have to configure `discordproxy`, see its documentation » https://discordproxy.readthedocs.io/en/latest/operations.html#docker-aa4

**Comment by Exenifix** [comment]
No, I can only configure on which port and on which port discordproxy RUNS. If you do not provide that in your app, it will use default settings as you can see from discordproxy documenation (`target` parameter of `DiscordClient` class): https://discordproxy.readthedocs.io/en/latest/package.html#module-discordproxy.client

Correct usage of discordproxy host and port configuration can be seen in **Discord Notify**: https://gitlab.com/ErikKalkoken/aa-discordnotify/-/blob/master/discordnotify/core.py?ref_type=heads#L54

**Comment by Exenifix** [comment]
@ppfeufer

**Comment by ppfeufer** [comment]
Interesting that this is not mentionede in the `discordproxy` documentation, apologies.

**Comment by Exenifix** [comment]
In my opinion, it would also be an option (and possibly a better one) to use discord webhooks in case of new request notification

**Comment by ppfeufer** [comment]
Not really, the number of webhooks a server can have is severely limited. I think the limit is 50, which sounds a lot, but it isn't.
