### ISSUE TITLE
No discord direct messages

### ISSUE THREAD

**Issue by paulipa** [ppfeufer/aa-srp#41]
Users do not receive a DMs when their SRP app is approved or rejected. Happened to struggle with this as I used your code as example on my own app but direct messages did not go out. Tried it also with our prod version of aa-srp.

Got it working with my own app with the following change and assuming it would fix it with aa-srp also:

https://github.com/ppfeufer/aa-srp/blob/master/aasrp/helper/notification.py#L35-L37

```
aadiscordbot.tasks.send_direct_message_by_user_id.delay(
            user_pk=user.pk, message_content=message
        )
```

should be instead
```
aadiscordbot.tasks.send_direct_message_by_user_id.delay(
            user.pk, message
        )
```

**Comment by ppfeufer** [comment]
It would be interesting to know why. Do you have anything in your logs regarding this?

**Comment by paulipa** [comment]
I did not manage to see any errors in the log regarding this. I also checked if the delayed task was created and it was but the messages never went out. Only message i could see in logs was ```[02/Jan/2022 12:15:02] DEBUG [allianceauth.notifications.managers:99] Invalided notification cache for user with pk 2
``` but i have no clue if it was related to this or not.

**Comment by ppfeufer** [comment]
>  I also checked if the delayed task was created and it was but the messages never went out.

That does sound a lot like an issue with AA Discordbot itself (https://github.com/pvyParts/allianceauth-discordbot)

> Only message i could see in logs was `[02/Jan/2022 12:15:02] DEBUG [allianceauth.notifications.managers:99] Invalided notification cache for user with pk 2`

This is from AA's notification system and has nothing to do with it (https://sourcegraph.com/gitlab.com/allianceauth/allianceauth@v2.9.x/-/blob/allianceauth/notifications/managers.py?L100:9#tab=references)
