### ISSUE TITLE
[Feature Request] Editable "additional info" on new SRP request

### ISSUE THREAD

**Issue by BroodLK** [ppfeufer/aa-srp#47]
### Context

In which context would you expect your suggested feature to be useful?
Allow auth owners to change the information that is being requested per SRP request

### Describe the feature you have in mind

Ability for admins to edit the "additional info" text on a new srp request

### Additional context

Add any other context or screenshots/mockups about the feature request here.
![image](https://user-images.githubusercontent.com/13304828/150846050-c529273d-d12b-45a5-b53f-6cb25d71c3c3.png)

**Comment by ppfeufer** [comment]
Elaborate please, what's wrong with the current text?

**Comment by BroodLK** [comment]
The FCs want to change the text to "Was any module changed per the request of the FC" and stop generating full AARs from everyone who submits SRP.

**Comment by ppfeufer** [comment]
> Was any module changed per the request of the FC

I mean, that is literally in there ...

![image](https://user-images.githubusercontent.com/2989985/150852106-d4f3969b-d858-4554-9182-139a30992c7b.png)

**Comment by BroodLK** [comment]
Yep. I know. However the rest of it is causing a lot of people to post entire AARs which I don't mind but apparently annoys some of my FCs/SRP reviewers. *shrugs*

**Comment by ppfeufer** [comment]
After getting some examples presented on Discord, I have to say, that is literally how SRP requests should look like and this is working as intended.
