### ISSUE TITLE
[Feature] Qualification check, exclude cargo value and base pay value

### ISSUE THREAD

**Issue by paulipa** [ppfeufer/aa-srp#5]
Disclaimer: have not checked out your plugin yet but here are some things that i have missed from the base SRP module so if you are burning some man hours to make the SRP module awesome here are my five cents.

So here is a suggestion and maybe something to brainstorm with if you want to spend some time on something that has been missing from the base module:

### a way to check if the zkill qualifies for SRP.
This would require some type of doctrine module where current doctrines could be saved. There is currently one but when we were using it like a year back it was too buggy to be used. However maybe it is more stable now and could be something to work with? This way you could skip building the needed blocks for what would be basically a complete doctrine module.

Once this issue is tackled by either using the current plugin in development or adding the needed models directly into this one then you could compare the ship fitting to the doctrine and add a simple check market for if the fit is a match or not a match. Maybe even match on meta level where meta levels are different but modules are correct and a exactly match. This basically eliminates the need from SRP managers to check out on the fit on zkill before they pay out for it.

### Option to exclude cargo value
An option to exclude cargo item value from the zkill value would be nice. Either a global setting or an additional column on the table.

### Option to set up base prices or multipliers for doctrines
Would require pretty much to have the qualification check implemented first after that some doctrines could have a base price that they pay out. This would make it simpler in situations when SRP is offered based on hull value or ship type like increased SRP for logi.

**Comment by ppfeufer** [comment]
Hey there, thanks for your ideas, but I fear I have to disappoint you slightly ...

> Once this issue is tackled by either using the current plugin in development or adding the needed models directly into this one then you could compare the ship fitting to the doctrine and add a simple check market for if the fit is a match or not a match. Maybe even match on meta level where meta levels are different but modules are correct and a exactly match. This basically eliminates the need from SRP managers to check out on the fit on zkill before they pay out for it.

All this app is doing is to fetch the basic information from zKillboard. Like, shiptype, value, victim name (to check if t's either the main or one of their registered alts). Currently there are no plans in storing the full kill mail information at all, which also would be out of scope for this app. So a comparison to any doctrine is not possible.

Also there is always the chance that FCs are changing fitting according to circumstances they face, which would make it pretty much impossible to automatically check if a fitting qualifies or not.

> An option to exclude cargo item value from the zkill value would be nice. Either a global setting or an additional column on the table.

Again, this would require to store/analyse the complete kill mail, which  this app does not do. This would also require quite some additional ESI calls which will slow down the whole process significantly.

> Option to set up base prices or multipliers for doctrines

This is an interesting one, which might be done at some point. Not sure how though, but I keep this one on my list for now. I don't promise anything though.

On the other hand, you already can define the payout individually for each request by clicking on the ISK value in the payout column. If the payout is not defined that way, it assumes the full amount from the zkillboard loss value.
