### ISSUE TITLE
Able to change SRP payout amount

### ISSUE THREAD

**Issue by paintballlaws** [ppfeufer/aa-srp#51]
### Bug Description

Able to change SRP payout amount after it has been approved and after the link is closed. This opens up a lot of issues with everyone being able to change, if this is an intended feature maybe move it its own permission?

### Steps to Reproduce

Make a link and add a kill to the link and hit payout accept and then you can change the amount freely and even do it after you close the link.

### Expected behavior

Don't want to allow changing SRP payout amount after approval except for higher tier permissions.

### Please complete the following information:

- AA-SRP Version: 1.11.0
- Alliance Auth Version: 2.10.1
- Browser and Version: Chrome

**Comment by ppfeufer** [comment]
Good point, thanks for bringing this up.

**Comment by ppfeufer** [comment]
I implemented a check that payout values for approved requests can no longer be changed. This means that the payout for rejected requests still can be changed, in case it was rejected accidentally and is approved later on. The overall SRP costs are now calculated by only taking approved requests into account though.
