### ISSUE TITLE
[Feature Request] Filter requests list to pending by default (when doing so is an option)

### ISSUE THREAD

**Issue by ksyntax** [ppfeufer/aa-srp#67]
### Context

When aa-srp is used for a long-lived general SRP program, rather than for separate short-lived request links per fleet or similar, the SRP manager is by default faced with a large list of requests which have already been processed and are no longer actionable.

### Describe the feature you have in mind

I would like to see the requests list filtered to "pending" by default, if pending requests exist. This reduces the noise viewed by an individual processing new SRP requests.

When there are no pending requests, the current behavior of reviewing all requests is appropriate.

**Comment by ppfeufer** [comment]
To my knowledge, DataTables does not support setting filters on initialisation/page load.
