### ISSUE TITLE
[Feature Request] Specify Payout Percentage on approving SRP

### ISSUE THREAD

**Issue by bubis7** [ppfeufer/aa-srp#72]
**Context**
When approving an a SRP link we would like to specify the percentage of SRP that is going to be paid out. As of now payout shows the full zkb value, bet in reality it could be something else. Option to specify what percentage has been paid out would be a nice improvement to most cases.  

**Describe the feature you have in mind**
When accepting an a SRP request have a field "Payout percentage" that could default to 100%, but can be edited. Would be awesome if that windows automatically calculates the percentage of the zkb value and makes a copyable amount to be paid out, so that  the person who processed the SRP can just copy the amount and pay it out.

**Comment by ppfeufer** [comment]
On pending or rejected SRP requests you can click on the number in the payout field to change it ...

![image](https://user-images.githubusercontent.com/2989985/179961750-bc32b132-7e09-4a4d-93ff-cb23cf1df1f7.png)

**Comment by bubis7** [comment]
Ohh didnt find anything about this in docs. Then this solves the issue we had :)

**Comment by ppfeufer** [comment]
It will be a bit more obvious in the next release

![image](https://user-images.githubusercontent.com/2989985/180175696-122fb4ed-100f-42ff-825f-65890b0692bc.png)
