### ISSUE TITLE
Alliance Character view their SRP request detail error

### ISSUE THREAD

**Issue by heguyChen** [ppfeufer/aa-srp#81]
### Bug Description

When alliance character put their SRR request info, and want to see their SRP Requests. When SRP is pending, and they click SRP request details , server send : xxx/view-additional-information-data and return to domain.com/account/login. 

### Steps to Reproduce

1. Go to 'domain.com/ship-replacement/'
2. Click on 'Your SRP Requests'
3. Click on 'SRP request details'
4. See error like this request url: https://domain.com/account/login/?next=/ship-replacement/ajax/srp-link/HeRpMFZ2Snn7S832/srp-request/m35bgxc38wFeFddG/view-additional-information-data/

### Screenshots

![image](https://user-images.githubusercontent.com/25737152/204077013-202d7226-a668-48fb-ad3b-ae729893b05d.png)

- App Version:
- Alliance Auth Version:3.2.0
- Browser and Version: Microsoft Edge 107.0.1418.56

by the way, alliance character permission is : aasrp | AA-SRP | Can access the AA-SRP module

**Comment by ppfeufer** [comment]
Hey there, thanks for reporting this.

There is indeed a mistake which puts this view behind the wrong permissions.
